package.json
server/api.js

#11- Feature api endpoints - Chioma [DEV]

---

server/database.sql

#9 - Feature/Database - Kerim [DEV]

---

client/src/App.css
client/src/App.js
client/src/components/Footer.js
client/src/pages/StudentDashboard.js

#26 - Feature/Footer - Kerim [MAIN]

---

client/src/components/FeedbackModal.js
client/src/components/Profile.js
client/src/components/Progress.js
client/src/pages/StudentDashboard.js
package.json
server/api.js
server/database.sql

Refactored profile, feedback form components to make them reusable 
Fixes #2pm 8

#28 - Feature/make reusable component - Saadia [MAIN]

---

client/src/components/StudentInfo.js
client/src/pages/MentorDashboard.js
client/src/pages/StudentDashboard.js
server/api.js

#40 - Feature/link get route/mentor - Chioma & Saadia [MAIN]

---

client/src/App.css
client/src/App.js
client/src/components/Footer.js
client/src/components/Navbar/Navbar.css
client/src/components/Navbar/Navbar.js
client/src/pages/Login.js

Added a navbar title and formatted styling
Fixes #51

#51-Featute/navbar-title-Saadia [DEV]

---

client/src/App.js
client/src/components/FeedbackModal.js
client/src/components/MentorFeedbackModal.js
client/src/components/NeutralButton.js
client/src/components/StudentInfo.js
client/src/components/StudentProfileMentor.js
client/src/components/StudentProfileModal.js
client/src/pages/StudentDashboard.js

#39 - Feature/student profile in mentor dashboard - Chioma [DEV]

---

client/src/pages/MentorDashboard.js
client/src/pages/StudentDashboard.js

#40 - Feature/link get route/mentor - Chioma & Saadia [MAIN] #56

---

client/src/components/Profile.js
client/src/components/StudentInfo.js
client/src/pages/MentorDashboard.js
client/src/pages/StudentDashboard.js
server/api.js

#42 - Feature/linking the frontend to backend put - Saadia, Kerim & Chioma [DEV]

---

client/src/components/Navbar/Navbar.js

Added logout functionality 
Fixes #49

#49-Feature/add logout functionality- Saadia [DEV]

---

client/src/App.js
client/src/components/MentorFeedbackModal.js
client/src/components/Navbar/Navbar.js
client/src/components/NeutralButton.js
client/src/components/Profile.js
client/src/components/StudentInfo.js
client/src/components/StudentProfileMentor.js
client/src/components/StudentProfileModal.js
client/src/pages/MentorDashboard.js
client/src/pages/StudentDashboard.js
server/api.js

Added logout functionality 
Fixes #49

#49-Feature/add logout functionality- Saadia [MAIN]

---

client/src/components/Progress.js
server/api.js

Fill modules and lessons dropdown from the database
Fixes #70

#70-Feature/Fill modules and lessons dropdown from the database-Saadia [DEV]

---

client/src/App.js
client/src/components/MentorFeedbackModal.js
client/src/components/Navbar/Navbar.js
client/src/components/NeutralButton.js
client/src/components/Profile.js
client/src/components/Progress.js
client/src/components/StudentInfo.js
client/src/components/StudentProfileMentor.js
client/src/components/StudentProfileModal.js
client/src/pages/MentorDashboard.js
client/src/pages/StudentDashboard.js
server/api.js

Fill modules and lessons dropdown from the database
Fixes #70

#70-Feature/Fill modules and lessons dropdown from the database-Saadia [MAIN]

---

client/src/components/MentorFeedbackModal.js

#39 - feature/student-profile-in-mentor-dashboard - Chioma [MAIN]

---

client/src/App.js
client/src/components/FeedbackModal.js
client/src/components/MentorFeedbackModal.js
client/src/components/Navbar/Navbar.js
client/src/components/Progress.js
client/src/components/StudentInfo.js
client/src/components/StudentProfile.js
client/src/components/StudentProfileMentor.js
client/src/components/StudentProfileModal.js
client/src/pages/MentorDashboard.js
client/src/pages/StudentDashboard.js
server/api.js

#43-Feature/post linking the frontend to backend- Saadia & Chioma [MAIN]

---

client/src/App.js
client/src/components/AddUser.js
client/src/components/BlackButton.js
client/src/pages/AdminDashboard.js
package.json
server/api.js

#59 - Feature/Admin dashboard - Kerim

---

client/src/pages/AdminDashboard.js

feature/GET request for Admin [DEV]

---

client/src/components/Profile.js
client/src/components/ResetPasswordForm.js
server/api.js

#60-Feature/reset password form-Saadia [MAIN]

---

client/src/components/AddUser.js
client/src/components/Navbar/Navbar.css
client/src/components/Navbar/Navbar.js
client/src/components/Profile.js
client/src/components/Progress.js
client/src/components/ResetPasswordForm.js
client/src/pages/AdminDashboard.js
client/src/pages/MentorDashboard.js
client/src/pages/StudentDashboard.js
package.json
server/api.js
server/app.js

Bugfix/fix issues -Saadia [MAIN]

---

client/src/components/AddUser.js
client/src/pages/Login.js
server/api.js

#69 - Feature/backend form validation and link to front - Chioma [MAIN]

---

client/src/App.js
client/src/components/TeamGridItem.js
client/src/data/team.js
client/src/pages/About.js
package.json
server/app.js
server/utils/middleware.js

Feature/refactore-about-Saadia [DEV]

---

client/src/App.js
client/src/components/TeamGridItem.js
client/src/data/team.js
client/src/pages/About.js

Feature/refactore-about-Saadia [MAIN]

---

client/src/components/Footer.js
client/src/index.html
client/src/pages/Login.js

Feature/display mentor feedback - Saadia [MAIN]

---

server/database.sql

#9 - Feature/new database - Kerim [MAIN]

---

README.md
server/database.sql

#9 - Feature/new database - Kerim [DEV]
